# Generated by Django 2.2.2 on 2019-06-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats_group', '0003_auto_20190623_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats_group_created', to='user.User'),
        ),
    ]
