# Generated by Django 2.2.2 on 2019-06-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats_group', '0004_auto_20190623_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='messages',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='users',
            field=models.ManyToManyField(related_name='chats', to='user.User'),
        ),
    ]
