# Generated by Django 2.2.2 on 2019-06-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_last_enter',
            field=models.DateTimeField(auto_now=True, max_length=255),
        ),
    ]
