# Generated by Django 2.2.2 on 2019-06-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_publication',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
