# Generated by Django 2.2.2 on 2019-06-27 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats_group', '0005_auto_20190627_0628'),
        ('message', '0002_auto_20190623_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chats_group.ChatGroup'),
        ),
    ]
